// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package v1

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CalculatingUniqueIdRequest defines model for CalculatingUniqueIdRequest.
type CalculatingUniqueIdRequest struct {
	Param1 string `json:"param1"`
	Param2 string `json:"param2"`
}

// CalculatingUniqueIdResponse defines model for CalculatingUniqueIdResponse.
type CalculatingUniqueIdResponse struct {
	Uuid string `json:"uuid"`
}

// Error defines model for Error.
type Error struct {
	Details string `json:"details"`
	Slug    string `json:"slug"`
}

// CalculatingIdJSONBody defines parameters for CalculatingId.
type CalculatingIdJSONBody CalculatingUniqueIdRequest

// CalculatingIdJSONRequestBody defines body for CalculatingId for application/json ContentType.
type CalculatingIdJSONRequestBody CalculatingIdJSONBody
